name: Publish Python Package

on:
  push:
    branches: [ main ]

jobs:
  build-publish:
    runs-on: ubuntu-latest  # 推荐使用 Linux 环境
    permissions:
      contents: write
      id-token: write  # 必须用于 PyPI 可信发布

    steps:
    - uses: actions/checkout@v4

    # 1. 严格验证项目结构
    - name: Validate Structure
      run: |
        echo "=== 文件结构验证 ==="
        [ -f pyproject.toml ] || { echo "❌ 缺少 pyproject.toml"; exit 1; }
        [ -f encrypt_tools_library/__init__.py ] || { echo "❌ 缺少 __init__.py"; exit 1; }
        
        echo "=== 版本一致性验证 ==="
        PYPROJECT_VER=$(grep -E '^version =' pyproject.toml | cut -d'"' -f2)
        INIT_VER=$(grep -E '__version__ =' encrypt_tools_library/__init__.py | cut -d'"' -f2)
        
        if [ "$PYPROJECT_VER" != "$INIT_VER" ]; then
          echo "❌ 版本不一致: pyproject=$PYPROJECT_VER ≠ __init__.py=$INIT_VER"
          exit 1
        fi

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    # 3. 安装构建工具
    - name: Install Build Tools
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    # 4. 清理构建环境
    - name: Clean Build Artifacts
      run: |
        rm -rf dist/ build/ *.egg-info/
        find . -name '__pycache__' -exec rm -rf {} +

    # 5. 构建并严格验证
    - name: Build Package
      run: |
        echo "=== 开始构建 ==="
        python -m build --wheel --no-isolation
        
        echo "=== 验证 Wheel 文件 ==="
        WHEEL_PATH=$(ls dist/*.whl)
        echo "生成文件: $WHEEL_PATH"
        
        echo "=== 提取元数据 ==="
        unzip -p "$WHEEL_PATH" "*.dist-info/METADATA" > metadata.txt
        echo "--- METADATA 内容 ---"
        cat metadata.txt
        
        echo "=== 关键字段检查 ==="
        grep -q "Name: encrypt_tools_library" metadata.txt || { echo "❌ 缺少 Name 字段"; exit 1; }
        grep -q "Version: $PYPROJECT_VER" metadata.txt || { echo "❌ 版本不匹配"; exit 1; }

    # 6. 发布到 PyPI
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        skip-existing: true
