name: Publish Python Package

on:
  push:
    branches: [ main ]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Validate Structure
      run: |
        [ -f pyproject.toml ] || exit 1
        [ -f encrypt_tools_library/__init__.py ] || exit 1
        PYPROJECT_VER=$(grep 'version =' pyproject.toml | cut -d'"' -f2)
        INIT_VER=$(grep '__version__' encrypt_tools_library/__init__.py | cut -d'"' -f2)
        [ "$PYPROJECT_VER" = "$INIT_VER" ] || exit 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Build Tools
      run: |
        pip install build wheel toml

    - name: Get version from pyproject.toml
      id: get_version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Git tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ steps.get_version.outputs.version }}
        message: "Release v${{ steps.get_version.outputs.version }}"

    - name: Build Package
      run: |
        rm -rf dist/ build/
        python -m build --wheel --no-isolation
        unzip -p dist/*.whl *dist-info/METADATA | grep "Name: encrypt-tools-library" || exit 1

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
